#!/bin/bash

#*
# Extract the specified values from the OPTIMADE JSON responses

# USAGE:
#     $0 optimade.json
#     ./optimade-cod-query 'elements+HAS+ALL+"Mg","O"+AND+nelements=2' | $0

#**

echo "codid,chemical_formula_hill,_cod_vol,_cod_diffrpressure,_cod_diffrtemp"

jq -r '
    .data[] | [ 
        .id,
        .attributes.chemical_formula_hill,
        .attributes._cod_vol, 
        .attributes._cod_diffrpressure,
        .attributes._cod_diffrtemp
    ]
    | @csv
' "$@"
