#!/bin/bash

#*
# Fetch structures from the COD (or any other database) using the
# OPTIMADE [1,2] interface.
#
# The script accepts any OPTIMADE Filter expression as an argument.
#
# USAGE:
#    $0 'elements+HAS+ALL+"Mg","O"+AND+nelements=2'
#
# Refs.:
#
# 1. OPTIMADE intreface specification (2022)
#    URL: https://github.com/Materials-Consortia/OPTIMADE
#    [accessed: 2022-05-30T10:14+03:00]
#
# 2. Andersen, Casper W. et al. OPTIMADE, an API for exchanging
#    materials data (2021) Scientific Data , Vol. 8, No. 1 Springer
#    Science and Business Media LLC p. 1-10, DOI:
#    https://doi.org/10.1038/s41597-021-00974-z
#**

# DEPENDENCIES:
# this script uses 'curl' and 'jq' commands.

TMP_DIR="${TMPDIR}"

# Set COD_OPTIMADE_SLEEP_TIME to different value in your environment
# to change this default:

test -z "${OPTIMADE_QUERY_SLEEP_TIME}" && OPTIMADE_QUERY_SLEEP_TIME=10

FILES=""
PROVIDER=""

set -ue
## set -x

#** USAGE:
#**   $0 --options file1.inp files*.inp
#**
#** OPTIONS:
#**  --provider cod           Specify which provider to query
#**  --help                   print short help message (this message) and exit
while [ $# -gt 0 ]
do
    case $1 in
        --version|--versio|--versi|--vers|--ver|--ve|--v)
            echo $Id
            exit
            ;;
        --provider|--provide|--provid|--provi|--prov|--pro|--pr|--p)
            PROVIDER="$2"
            shift
            ;;
        --help|--hel|--he|--h)
            awk '/#\*/,/#\*\*/ {
                    sub("^ *#[*]?[*]?", ""); \
                    gsub("\\$0","'$0'"); \
                    print $0
                }' $0
	    exit
	    ;;
        --options|--option)
            echo "$0: '--options' is a place-holder; " \
                 "please use '$0 --help' to get the list of available options."
            exit 2
            ;;
        -*) echo "$0: unknown option '$1'" >&2 ; exit 1 ;;
        *)  FILES="$FILES '$1'" ;;
    esac
    shift
done

## echo ${FILES}
eval set -- "${FILES}"

declare -A providers

providers["aflow"]="http://aflow.org/API/optimade/"
providers["cod"]="https://www.crystallography.net/cod/optimade"
providers["sssp"]="https://aiida.materialscloud.org/sssplibrary/optimade"
providers["2dstructures"]="https://aiida.materialscloud.org/2dstructures/optimade"
providers["2dtopo"]="https://aiida.materialscloud.org/2dtopo/optimade"
providers["tc-applicability"]="https://aiida.materialscloud.org/tc-applicability/optimade"
providers["threedd"]="https://aiida.materialscloud.org/3dd/optimade"
providers["mc3d-structures"]="https://aiida.materialscloud.org/mc3d-structures/optimade"
providers["scdm"]="https://aiida.materialscloud.org/autowannier/optimade"
providers["curated-cofs"]="https://aiida.materialscloud.org/curated-cofs/optimade"
providers["optimade-sample"]="https://aiida.materialscloud.org/optimade-sample/optimade"
providers["stoceriaitf"]="https://aiida.materialscloud.org/stoceriaitf/optimade"
providers["pyrene-mofs"]="https://aiida.materialscloud.org/pyrene-mofs/optimade"
providers["li-ion-conductors"]="https://aiida.materialscloud.org/li-ion-conductors/optimade"
providers["tin-antimony-sulfoiodide"]="https://aiida.materialscloud.org/tin-antimony-sulfoiodide/optimade"
providers["mp"]="https://optimade.materialsproject.org"
providers["mpds"]="https://api.mpds.io"
providers["nmd"]="https://nomad-lab.eu/prod/rae/optimade/"
providers["odbx"]="https://optimade.odbx.science"
providers["omdb_production"]="http://optimade.openmaterialsdb.se"
providers["oqmd"]="http://oqmd.org/optimade/"
providers["jarvis"]="https://jarvis.nist.gov/optimade/jarvisdft"
providers["tcod"]="https://www.crystallography.net/tcod/optimade"
providers["twodmatpedia"]="http://optimade.2dmatpedia.org"

FILTER="$1" # will report an error if the first argument is not defined

case "$0" in
    *-cod-*)
        PROVIDER="cod"
        ;;
    *-tcod-*)
        PROVIDER="tcod"
        ;;
    *-aflow-*)
        PROVIDER="aflow"
        ;;
    *-nomad-*)
        PROVIDER="nmd"
        ;;
    *-omdb-*)
        PROVIDER="omdb_production"
        ;;
    *-mp-*)
        PROVIDER="mp"
        ;;
esac

if [ "${PROVIDER}" = "" ]
then
    NCOMPONENTS=$(basename $0 | awk -F- '{print NF}')
    if [ $NCOMPONENTS -gt 3 ]
    then
        PROVIDER=$(basename $0 | awk -F- '{print $2}')
    fi
fi

OPTIMADE_SRV="${providers[${PROVIDER}]}/v1"
OPTIMADE_URI="${OPTIMADE_SRV}/structures"

BASENAME="$(basename $0)"

test -z "${TMP_DIR}" && TMP_DIR="/tmp"
TMP_DIR="${TMP_DIR}/tmp-${BASENAME}-$$"
mkdir "${TMP_DIR}"

TMP_RESPONSE="${TMP_DIR}/response.json"
TMP_HEADER="${TMP_DIR}/http-header.txt"

# To make the trap portable between bash and dash, we need to trap
# "signal" 0 ("EXIT") and rely on it for the cleanup:
## trap "rm -rf '${TMP_DIR}'" 0 1 2 3 15
trap "rm -rf '${TMP_DIR}'" EXIT
trap "exit 1" HUP INT QUIT TERM

## set -x

MORE_DATA=true
CURRENT_URI="${OPTIMADE_URI}?filter=$FILTER"

while [ $MORE_DATA = true ]
do
    if [ -n "${OPTIMADE_QUERY_VERBOSE:-""}" ]
    then
        echo "$0: NOTE, querying '${CURRENT_URI}'" >&2
    fi
    
    curl -sSL -D "${TMP_HEADER}" "${CURRENT_URI}" > "${TMP_RESPONSE}"

    STATUS="$?"
    if ! [ $STATUS -eq 0 ] ||
       ! cat "${TMP_HEADER}" | grep -qP '200 OK|HTTP/2\s*200'
    then
        echo "$0: ERROR, curl could not fetch data from '${CURRENT_URI}':" >&2
        echo "$0: curl return status = '$STATUS'" >&2
        echo "$0: HTTP header:" >&2
        cat "${TMP_HEADER}" | awk '{print " ",$0}' >&2
        exit 2
    fi
    
    MORE_DATA=$(jq -r '.meta.more_data_available' "${TMP_RESPONSE}")
    CURRENT_URI=$(jq -r '.links.next' "${TMP_RESPONSE}")

    if [[ "${CURRENT_URI}" =~ '"href":' ]]
    then
        CURRENT_URI=$(jq -r '.links.next.href' "${TMP_RESPONSE}")
    fi

    if [[ "${CURRENT_URI}" = null ]]
    then
        CURRENT_URI=$(jq -r '.meta.next' "${TMP_RESPONSE}")
    fi
    
    if ! [[ "${CURRENT_URI}" =~ ^http ]]
    then
        CURRENT_URI="${OPTIMADE_SRV}${CURRENT_URI}"
    fi
    
    ## echo $0: MORE_DATA=${MORE_DATA} NEXT_URI="${CURRENT_URI}"

    cat "${TMP_RESPONSE}"

    rm -f "${TMP_RESPONSE}"
    
    sleep ${OPTIMADE_QUERY_SLEEP_TIME}
    
    ## MORE_DATA=false
done
